apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginprofile-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loginprofile-app
  template:
    metadata:
      labels:
        app: loginprofile-app
    spec:
      containers:
      - name: loginprofile-app
        image: aswinsagar/loginprofile:latest
        ports:
        - containerPort: 3000
        # env:
        # - name: MONGO_URI
        #   value: mongodb://mongo:27017/loginprofile
---
apiVersion: v1
kind: Service
metadata:
  name: loginprofile-app
spec:
  selector:
    app: loginprofile-app
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer