name: Deploy to GKE

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}' # Use secret containing your service account JSON

    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v1
    #   with:
    #     terraform_version: 0.14.8

    # - name: Apply Terraform
    #   run: |
    #     terraform init
    #     terraform apply -auto-approve

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: loginprofile-cluster   # Replace with your actual cluster name
        location: us-central1-a              # Replace with your cluster location
        project_id: loginprofile123           # Your project ID

    - name: Deploy to GKE
      run: |
        kubectl apply -f Deployment.yml
      # env:
      #   KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    # - name: Deploy to GKE
    #   uses: google-github-actions/deploy-gke@v0.1
    #   with:
    #     image: aswinsagar/loginprofile:v1:${{ github.sha }}
    #     cluster_name: loginprofile-cluster   # Replace with your actual cluster name
    #     location: us-central1-a              # Replace with your cluster location
    #     project_id: loginprofile123           # Your project ID
    #     namespace: default                    # Change if necessary
